apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-seminario
  labels:
    app: api-seminario
    contexto: seminario-sre
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25% 
  replicas: 1
  selector:
    matchLabels:
      app: api-seminario
  template:
    metadata:
      labels:
        app: api-seminario
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000   # Define explicitamente um usuário não-privilegiado
      
      containers:
      - name: api
        image: api-seminario:v2
        imagePullPolicy: Never
        ports:
        - containerPort: 8080

        # TESTE DE CRASH (RESILIENCIA)
        # DevSecOps: Blindagem (Hardening) do tempo de execução
        securityContext:
          readOnlyRootFilesystem: true  # Impede escrita no sistema de arquivos do container (anti-malware)
          allowPrivilegeEscalation: false # Garante que o processo filho não ganhe mais privilégios que o pai
          capabilities:
            drop: ["ALL"] # Remove todas as permissões do Linux não essenciais (Princípio do Menor Privilégio)

        # SRE: Liveness Probe - "O processo está travado?" 
        # Se falhar 5 vezes, o K8s reinicia o container automaticamente (Self-healing).
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 5

        # SRE: Readiness Probe - "A aplicação pode receber tráfego?"
        # Se falhar, o Pod é removido do balanceamento do Service, mas não é reiniciado.
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 1
          periodSeconds: 2
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3

        resources:
          requests:
            cpu: "30m"      
          # memory: "64Mi"  # Não usando propositalmente, mas pode ser ajustado conforme a necessidade da aplicação.
          limits:
            cpu: "60m"      
          # memory: "128Mi" # Não usando propositalmente, mas pode ser ajustado conforme a necessidade da aplicação. para evitar OOMKills, é recomendado definir limites de memória.

        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume

      volumes:
      - name: tmp-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: api-seminario-svc
spec:
  type: NodePort
  selector:
    app: api-seminario
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
---
# TESTE DE CARGA (ESCALABILIDADE)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-seminario-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-seminario
  minReplicas: 1
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70 # Escala horizontalmente quando a CPU média exceder 70%